In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = np.load("FashionMNIST0.6.npz")

In [3]:
#load the dataset and check the shape of attributes 
Xtr_val = dataset["Xtr"]
Str_val = dataset["Str"]
Xts = dataset["Xts"]
Yts = dataset["Yts"]

print(Xtr_val.shape)
print(Str_val.shape)
print(Xts.shape)
print(Yts.shape)

(18000, 28, 28)
(18000,)
(3000, 28, 28)
(3000,)


In [4]:
#reshape to matrices
Xtr_val = Xtr_val.reshape(-1, 28*28)
Xts = Xts.reshape(-1, 28*28)

In [5]:
from sklearn.model_selection import train_test_split

In [14]:
#Logistic Regression Classifier Classifier Estimator
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(multi_class = "multinomial", solver = "newton-cg")

clf1.fit(Xtr_val, Str_val)
    
# Estimate Transition Matrix
predict_noise1 = clf1.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise1[:,0]))    # 1st column max number index
print(np.argmax(predict_noise1[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise1[:,2]))    # 3rd column max number index

2724
1881
2436


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [15]:
transition_matrix = np.array([predict_noise1[2724], predict_noise1[1881], predict_noise1[2436]])
transition_matrix

array([[9.98844802e-01, 5.55254776e-04, 5.99943056e-04],
       [3.48578063e-08, 9.99901518e-01, 9.84475002e-05],
       [7.92786245e-09, 3.25789530e-03, 9.96742097e-01]])

In [12]:
#Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(multi_class = "multinomial", solver = "newton-cg")

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf1.fit(X_train, y_train)
    
    matrix = np.array([[0.4, 0.3, 0.3],[0.3, 0.4, 0.3],[0.3, 0.3, 0.4]])
    matrix_inv = np.linalg.pinv(matrix)

    predict_noise1 = clf1.predict_proba(X_test)
    predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

    predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
    predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

    print((predict_result_clean1 == y_test).mean()) #adjusted
    print((predict_result_noise1 == y_test).mean()) 

/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.43833333333333335
0.43805555555555553


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.45694444444444443
0.44027777777777777


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.45
0.4486111111111111


KeyboardInterrupt: 

In [22]:
clf1.fit(Xtr_val, Str_val)
matrix = np.array([[0.4, 0.3, 0.3],[0.3, 0.4, 0.3],[0.3, 0.3, 0.4]])
matrix_inv = np.linalg.pinv(matrix)

predict_noise1 = clf1.predict_proba(Xts)
predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

print((predict_result_clean1 == Yts).mean()) #adjusted
print((predict_result_clean1 == Yts).std()) #adjusted
print((predict_result_noise1 == Yts).mean()) 
print((predict_result_noise1 == Yts).std()) 

0.609
0.48797438457361664
0.609
0.48797438457361664


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [8]:
#AdaBoost Classifier Estimator
from sklearn.ensemble import AdaBoostClassifier
clf2 = AdaBoostClassifier(n_estimators=10)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf2.fit(X_train, y_train)

    predict_noise2 = clf2.predict_proba(X_test)

    predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

    print((predict_result_noise2 == y_test).mean()) 
    print((predict_result_noise2 == y_test).std())

0.38666666666666666
0.4869861964733246
0.3819444444444444
0.485863031936439
0.3775
0.48476153931598165
0.395
0.48885069295235745
0.37027777777777776
0.48287901700294295
0.37333333333333335
0.4836895239257881
0.3838888888888889
0.48633137866740944
0.3894444444444444
0.48762431146919083
0.3977777777777778
0.48943908434446737
0.3863888888888889
0.48692146741758957


In [9]:
# Estimate Transition Matrix
predict_noise2 = clf2.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise2[:,0]))    # 1st column max number index
print(np.argmax(predict_noise2[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise2[:,2]))    # 3rd column max number index

1798
2171
878


In [10]:
transition_matrix = np.array([predict_noise2[1798], predict_noise2[2171], predict_noise2[878]])
transition_matrix

array([[0.3600211 , 0.32229192, 0.31768698],
       [0.33308916, 0.3758104 , 0.29110043],
       [0.32067969, 0.32665007, 0.35267024]])

In [6]:
#AdaBoost Classifier
from sklearn.ensemble import AdaBoostClassifier
clf2 = AdaBoostClassifier(n_estimators=10)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf2.fit(X_train, y_train)
    
    matrix = np.array([[0.4, 0.3, 0.3],[0.3, 0.4, 0.3],[0.3, 0.3, 0.4]])
    matrix_inv = np.linalg.pinv(matrix)


    predict_noise2 = clf2.predict_proba(X_test)
    predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

    predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
    predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

    print((predict_result_clean2 == y_test).mean()) #adjusted
    print((predict_result_clean2 == y_test).std())
    print((predict_result_noise2 == y_test).mean()) 
    print((predict_result_noise2 == y_test).std())

0.3736111111111111
0.4837621820331061
0.375
0.4841229182759271
0.38555555555555554
0.48672627742479907
0.38805555555555554
0.48730733768128776
0.36444444444444446
0.48127402938245556
0.36694444444444446
0.4819711808145819
0.3838888888888889
0.48633137866740944
0.3883333333333333
0.48737106557073695
0.3705555555555556
0.48295355449822414
0.37222222222222223
0.48339718607597704
0.38
0.48538644398046393
0.37694444444444447
0.48462081078603464
0.37805555555555553
0.4849015904996969
0.37833333333333335
0.48497136227020887
0.3825
0.48599768517967235
0.385
0.48659531440407444
0.38222222222222224
0.4859304426167684
0.3838888888888889
0.48633137866740944
0.38305555555555554
0.48613166623208187
0.38305555555555554
0.48613166623208187


In [20]:
clf2.fit(Xtr_val, Str_val)
matrix = np.array([[0.4, 0.3, 0.3],[0.3, 0.4, 0.3],[0.3, 0.3, 0.4]])
matrix_inv = np.linalg.pinv(matrix)

predict_noise2 = clf2.predict_proba(Xts)
predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

print((predict_result_clean2 == Yts).mean()) #adjusted
print((predict_result_clean2 == Yts).std()) #adjusted

print((predict_result_noise2 == Yts).mean()) 
print((predict_result_noise2 == Yts).std()) 

0.8153333333333334
0.3880269177375313
0.795
0.40370162248868907


In [11]:
#RandomForest Classifier Classifier Estimator
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=10,max_depth=7)

clf3.fit(Xtr_val, Str_val)
    
# Estimate Transition Matrix
predict_noise3 = clf3.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise3[:,0]))    # 1st column max number index
print(np.argmax(predict_noise3[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise3[:,2]))    # 3rd column max number index

1008
2168
1402


In [13]:
transition_matrix = np.array([predict_noise3[1008], predict_noise3[2168], predict_noise3[1402]])
transition_matrix

array([[0.59738294, 0.20111096, 0.2015061 ],
       [0.17529175, 0.68595751, 0.13875074],
       [0.21934629, 0.22855546, 0.55209824]])

In [24]:
# RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=10,max_depth=7)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf3.fit(X_train, y_train)
    
    matrix = np.array([[0.4, 0.3, 0.3],[0.3, 0.4, 0.3],[0.3, 0.3, 0.4]])
    matrix_inv = np.linalg.pinv(matrix)

    predict_noise3 = clf3.predict_proba(X_test)
    predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

    predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
    predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

    print((predict_result_clean3 == y_test).mean()) #adjusted
    print((predict_result_clean3 == y_test).std()) #adjusted
    print((predict_result_noise3 == y_test).mean()) 
    print((predict_result_noise3 == y_test).std()) 

0.37
0.4828043081829324
0.37
0.4828043081829324
0.3869444444444444
0.4870507585026685
0.3869444444444444
0.4870507585026685
0.38083333333333336
0.4855917066379486
0.38083333333333336
0.4855917066379486
0.37694444444444447
0.48462081078603464
0.37694444444444447
0.48462081078603464
0.3763888888888889
0.48447940431960224
0.3763888888888889
0.48447940431960224
0.37027777777777776
0.48287901700294295
0.37027777777777776
0.48287901700294295
0.3819444444444444
0.485863031936439
0.3819444444444444
0.485863031936439
0.36972222222222223
0.48272942795864837
0.36972222222222223
0.48272942795864837
0.37305555555555553
0.48361669535355317
0.37305555555555553
0.48361669535355317
0.39166666666666666
0.48812282152024905
0.39166666666666666
0.48812282152024905


In [25]:
clf3.fit(Xtr_val, Str_val)
matrix = np.array([[0.4, 0.3, 0.3],[0.3, 0.4, 0.3],[0.3, 0.3, 0.4]])
matrix_inv = np.linalg.pinv(matrix)

predict_noise3 = clf3.predict_proba(Xts)
predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

print((predict_result_clean3 == Yts).mean()) #adjusted
print((predict_result_clean3 == Yts).std())

print((predict_result_noise3 == Yts).mean()) 
print((predict_result_noise3 == Yts).std())

0.7943333333333333
0.4041879375845955
0.7943333333333333
0.4041879375845955
