In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = np.load("FashionMNIST0.5.npz")

In [3]:
#load the dataset and check the shape of attributes 
Xtr_val = dataset["Xtr"]
Str_val = dataset["Str"]
Xts = dataset["Xts"]
Yts = dataset["Yts"]

print(Xtr_val.shape)
print(Str_val.shape)
print(Xts.shape)
print(Yts.shape)

(18000, 28, 28)
(18000,)
(3000, 28, 28)
(3000,)


In [4]:
#reshape to matrices
Xtr_val = Xtr_val.reshape(-1, 28*28)
Xts = Xts.reshape(-1, 28*28)

In [5]:
from sklearn.model_selection import train_test_split

In [14]:
#Logistic Regression Classifier Classifier Estimator
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(multi_class = "multinomial", solver = "newton-cg")

clf1.fit(Xtr_val, Str_val)
    
# Estimate Transition Matrix
predict_noise1 = clf1.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise1[:,0]))    # 1st column max number index
print(np.argmax(predict_noise1[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise1[:,2]))    # 3rd column max number index

919
2724
2598


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [15]:
transition_matrix = np.array([predict_noise1[919], predict_noise1[2724], predict_noise1[2598]])
transition_matrix

array([[9.99952084e-01, 4.79159630e-05, 4.47293996e-11],
       [4.82152803e-03, 9.95148434e-01, 3.00380142e-05],
       [3.90790291e-03, 8.44221891e-04, 9.95247875e-01]])

In [6]:
#Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(multi_class = "multinomial", solver = "newton-cg")

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf1.fit(X_train, y_train)
    
    matrix = np.array([[0.5, 0.2, 0.3],[0.3, 0.5, 0.2],[0.2, 0.3, 0.5]])
    matrix_inv = np.linalg.pinv(matrix)

    predict_noise1 = clf1.predict_proba(X_test)
    predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

    predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
    predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

    print((predict_result_clean1 == y_test).mean()) #adjusted
    print((predict_result_noise1 == y_test).mean()) 

/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.45055555555555554
0.43833333333333335


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.45
0.44


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.4613888888888889
0.45055555555555554


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.44666666666666666
0.44055555555555553


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.43194444444444446
0.4272222222222222


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.44333333333333336
0.4386111111111111


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.45111111111111113
0.4375


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.4425
0.4311111111111111


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


0.45305555555555554
0.4452777777777778
0.44055555555555553
0.4313888888888889


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [22]:
clf1.fit(Xtr_val, Str_val)
matrix = np.array([[0.5, 0.2, 0.3],[0.3, 0.5, 0.2],[0.2, 0.3, 0.5]])
matrix_inv = np.linalg.pinv(matrix)

predict_noise1 = clf1.predict_proba(Xts)
predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

print((predict_result_clean1 == Yts).mean()) #adjusted
print((predict_result_clean1 == Yts).std()) #adjusted
print((predict_result_noise1 == Yts).mean()) 
print((predict_result_noise1 == Yts).std()) 

0.805
0.39620070671315066
0.7746666666666666
0.4178016541640569


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [16]:
#AdaBoost Classifier Classifier Estimator
from sklearn.ensemble import AdaBoostClassifier
clf2 = AdaBoostClassifier(n_estimators=10)

clf2.fit(Xtr_val, Str_val)
    
# Estimate Transition Matrix
predict_noise2 = clf2.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise2[:,0]))    # 1st column max number index
print(np.argmax(predict_noise2[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise2[:,2]))    # 3rd column max number index

2838
228
1642


In [17]:
transition_matrix = np.array([predict_noise2[2838], predict_noise2[228], predict_noise2[1642]])
transition_matrix

array([[0.36497251, 0.32507217, 0.30995532],
       [0.33099982, 0.36433796, 0.30466222],
       [0.32590735, 0.31537514, 0.35871751]])

In [6]:
#AdaBoost Classifier
from sklearn.ensemble import AdaBoostClassifier
clf2 = AdaBoostClassifier(n_estimators=10)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf2.fit(X_train, y_train)
    
    matrix = np.array([[0.5, 0.2, 0.3],[0.3, 0.5, 0.2],[0.2, 0.3, 0.5]])
    matrix_inv = np.linalg.pinv(matrix)


    predict_noise2 = clf2.predict_proba(X_test)
    predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

    predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
    predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

    print((predict_result_clean2 == y_test).mean()) #adjusted
    print((predict_result_clean2 == y_test).std())
    print((predict_result_noise2 == y_test).mean()) 
    print((predict_result_noise2 == y_test).std())

0.4691666666666667
0.47944444444444445
0.45694444444444443
0.45555555555555555
0.4625
0.4622222222222222
0.46305555555555555
0.46194444444444444
0.4738888888888889
0.4775
0.4572222222222222
0.45361111111111113
0.4697222222222222
0.4713888888888889
0.4638888888888889
0.4622222222222222
0.4583333333333333
0.45611111111111113
0.4672222222222222
0.4691666666666667


In [23]:
clf2.fit(Xtr_val, Str_val)
matrix = np.array([[0.5, 0.2, 0.3],[0.3, 0.5, 0.2],[0.2, 0.3, 0.5]])
matrix_inv = np.linalg.pinv(matrix)

predict_noise2 = clf2.predict_proba(Xts)
predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

print((predict_result_clean2 == Yts).mean()) #adjusted
print((predict_result_clean2 == Yts).std()) #adjusted

print((predict_result_noise2 == Yts).mean()) 
print((predict_result_noise2 == Yts).std()) 

0.8673333333333333
0.3392141244438713
0.857
0.3500728495613449


In [18]:
#RandomForest Classifier Classifier Estimator
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=10,max_depth=7)

clf3.fit(Xtr_val, Str_val)
    
# Estimate Transition Matrix
predict_noise3 = clf3.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise3[:,0]))    # 1st column max number index
print(np.argmax(predict_noise3[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise3[:,2]))    # 3rd column max number index

1390
1570
100


In [19]:
transition_matrix = np.array([predict_noise3[1390], predict_noise3[1570], predict_noise3[100]])
transition_matrix

array([[0.66563383, 0.17216733, 0.16219884],
       [0.19490638, 0.62997496, 0.17511866],
       [0.2565465 , 0.15887165, 0.58458186]])

In [10]:
# RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=10,max_depth=7)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf3.fit(X_train, y_train)
    
    matrix = np.array([[0.5, 0.2, 0.3],[0.3, 0.5, 0.2],[0.2, 0.3, 0.5]])
    matrix_inv = np.linalg.pinv(matrix)

    predict_noise3 = clf3.predict_proba(X_test)
    predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

    predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
    predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

    print((predict_result_clean3 == y_test).mean()) #adjusted
    print((predict_result_clean3 == y_test).std()) #adjusted
    print((predict_result_noise3 == y_test).mean()) 
    print((predict_result_noise3 == y_test).std()) 

0.47333333333333333
0.4713888888888889
0.47805555555555557
0.47638888888888886
0.4975
0.49833333333333335
0.48083333333333333
0.4811111111111111
0.4716666666666667
0.4747222222222222
0.4738888888888889
0.4716666666666667
0.4786111111111111
0.4786111111111111
0.4736111111111111
0.4661111111111111
0.47333333333333333
0.47305555555555556
0.4772222222222222
0.47444444444444445


In [24]:
clf3.fit(Xtr_val, Str_val)
matrix = np.array([[0.5, 0.2, 0.3],[0.3, 0.5, 0.2],[0.2, 0.3, 0.5]])
matrix_inv = np.linalg.pinv(matrix)

predict_noise3 = clf3.predict_proba(Xts)
predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

print((predict_result_clean3 == Yts).mean()) #adjusted
print((predict_result_clean3 == Yts).std())

print((predict_result_noise3 == Yts).mean()) 
print((predict_result_noise3 == Yts).std())

0.8973333333333333
0.30352301761517564
0.8896666666666667
0.313304785933584
