In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = np.load("CIFAR.npz")

In [3]:
#load the dataset and check the shape of attributes 
Xtr_val = dataset["Xtr"]
Str_val = dataset["Str"]
Xts = dataset["Xts"]
Yts = dataset["Yts"]

print(Xtr_val.shape)
print(Str_val.shape)
print(Xts.shape)
print(Yts.shape)

(15000, 32, 32, 3)
(15000,)
(3000, 32, 32, 3)
(3000,)


In [4]:
#reshape to matrices
Xtr_val = Xtr_val.reshape(-1, 32*32*3)
Xts = Xts.reshape(-1, 32*32*3)

In [5]:
from sklearn.model_selection import train_test_split

In [69]:
#Logistic Regression Classifier Estimator
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(multi_class = "multinomial", solver = "newton-cg")

clf1.fit(Xtr_val, Str_val)
    
# Estimate Transition Matrix
predict_noise1 = clf1.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise1[:,0]))    # 1st column max number index
print(np.argmax(predict_noise1[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise1[:,2]))    # 3rd column max number index

2114
1073
130


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [56]:
transition_matrix = np.array([predict_noise1[2114], predict_noise1[1073], predict_noise1[130]])
transition_matrix

array([[9.99989453e-01, 8.57537408e-06, 1.97156130e-06],
       [6.16290383e-07, 9.99674590e-01, 3.24794149e-04],
       [7.39503623e-04, 3.46226219e-06, 9.99257034e-01]])

In [ ]:
#Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(multi_class = "multinomial", solver = "newton-cg")

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf1.fit(X_train, y_train)
    
    matrix_inv = np.linalg.pinv(transition_matrix)

    predict_noise1 = clf1.predict_proba(X_test)
    predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

    predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
    predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

    print((predict_result_clean1 == y_test).mean()) #adjusted
    print((predict_result_noise1 == y_test).mean()) 

In [67]:
clf1.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(transition_matrix)

predict_noise1 = clf1.predict_proba(Xts)
predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

print((predict_result_clean1 == Yts).mean()) #adjusted
print((predict_result_clean1 == Yts).std()) #adjusted
print((predict_result_noise1 == Yts).mean()) 
print((predict_result_noise1 == Yts).std()) 

KeyboardInterrupt: 

In [70]:
matrix1 = np.array([[0.5, 0.2, 0.3],[0.3, 0.5, 0.2],[0.2, 0.3, 0.5]])
matrix2 = np.array([[0.4, 0.3, 0.3],[0.3, 0.4, 0.3],[0.3, 0.3, 0.4]])

In [77]:
clf1.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(matrix1)

predict_noise1 = clf1.predict_proba(Xts)
predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

print((predict_result_clean1 == Yts).mean()) #adjusted
print((predict_result_clean1 == Yts).std()) #adjusted
print((predict_result_noise1 == Yts).mean()) 
print((predict_result_noise1 == Yts).std()) 

0.37766666666666665
0.48480362576568625
0.37066666666666664
0.4829833215431863


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [78]:
clf1.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(matrix2)

predict_noise1 = clf1.predict_proba(Xts)
predict_noise_adjusted1 = np.dot(matrix_inv, predict_noise1.T)

predict_result_clean1 = np.argmax(predict_noise_adjusted1, axis = 0)
predict_result_noise1 = np.argmax(predict_noise1, axis = 1)

print((predict_result_clean1 == Yts).mean()) #adjusted
print((predict_result_clean1 == Yts).std()) #adjusted
print((predict_result_noise1 == Yts).mean()) 
print((predict_result_noise1 == Yts).std()) 

0.37066666666666664
0.4829833215431863
0.37066666666666664
0.4829833215431863


/Users/myeumuh/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [ ]:
#AdaBoost Classifier Estimator
from sklearn.ensemble import AdaBoostClassifier
clf2 = AdaBoostClassifier(n_estimators=10)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf2.fit(X_train, y_train)

#    predict_noise2 = clf2.predict_proba(X_test)

#    predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

#    print((predict_result_noise2 == y_test).mean()) 
#    print((predict_result_noise2 == y_test).std())

In [64]:
# Estimate Transition Matrix
predict_noise2 = clf2.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise2[:,0]))    # 1st column max number index
print(np.argmax(predict_noise2[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise2[:,2]))    # 3rd column max number index

1071
1458
477


In [65]:
transition_matrix = np.array([predict_noise2[1071], predict_noise2[1458], predict_noise2[477]])
transition_matrix

array([[0.3432841 , 0.34645369, 0.31026221],
       [0.30361172, 0.37226126, 0.32412701],
       [0.3187501 , 0.32632349, 0.35492641]])

In [25]:
#AdaBoost Classifier
from sklearn.ensemble import AdaBoostClassifier
clf2 = AdaBoostClassifier(n_estimators=10)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf2.fit(X_train, y_train)
    
    matrix_inv = np.linalg.pinv(transition_matrix)

    predict_noise2 = clf2.predict_proba(X_test)
    predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

    predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
    predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

    print((predict_result_clean2 == y_test).mean()) #adjusted
    print((predict_result_clean2 == y_test).std()) #adjusted
    print((predict_result_noise2 == y_test).mean()) 
    print((predict_result_noise2 == y_test).std())

0.36233333333333334
0.48067441047853676
0.3636666666666667
0.4810542819913593
0.3343333333333333
0.4717568818316862
0.3396666666666667
0.47359605384992626
0.36033333333333334
0.4800970966608965
0.36566666666666664
0.48161660639512377
0.35333333333333333
0.4780051138731561
0.357
0.47911480878803986
0.36
0.48000000000000004
0.36933333333333335
0.482624307533533
0.347
0.4760157560417512
0.3516666666666667
0.47749054673597696
0.3453333333333333
0.47547683668315777
0.342
0.47437959483940706
0.354
0.4782091592598368
0.356
0.4788152044369519
0.35333333333333333
0.4780051138731561
0.35533333333333333
0.47861420325305387
0.3393333333333333
0.4734830749057692
0.3436666666666667
0.47493145704289674


In [66]:
clf2.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(transition_matrix)

predict_noise2 = clf2.predict_proba(Xts)
predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

print((predict_result_clean2 == Yts).mean()) #adjusted
print((predict_result_clean2 == Yts).std()) #adjusted

print((predict_result_noise2 == Yts).mean()) 
print((predict_result_noise2 == Yts).std()) 

0.3873333333333333
0.4871408648658232
0.515
0.4997749493522059


In [72]:
clf2.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(matrix1)

predict_noise2 = clf2.predict_proba(Xts)
predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

print((predict_result_clean2 == Yts).mean()) #adjusted
print((predict_result_clean2 == Yts).std()) #adjusted

print((predict_result_noise2 == Yts).mean()) 
print((predict_result_noise2 == Yts).std()) 

0.561
0.49626505014961514
0.515
0.4997749493522059


In [73]:
clf2.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(matrix2)

predict_noise2 = clf2.predict_proba(Xts)
predict_noise_adjusted2 = np.dot(matrix_inv, predict_noise2.T)

predict_result_clean2 = np.argmax(predict_noise_adjusted2, axis = 0)
predict_result_noise2 = np.argmax(predict_noise2, axis = 1)

print((predict_result_clean2 == Yts).mean()) #adjusted
print((predict_result_clean2 == Yts).std()) #adjusted

print((predict_result_noise2 == Yts).mean()) 
print((predict_result_noise2 == Yts).std()) 

0.515
0.4997749493522059
0.515
0.4997749493522059


In [35]:
#RandomForest Classifier Estimator
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=10,max_depth=7)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf3.fit(X_train, y_train)

#    predict_noise3 = clf3.predict_proba(X_test)

 #   predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

  #  print((predict_result_noise3 == y_test).mean()) 
   # print((predict_result_noise3 == y_test).std())

0.3516666666666667
0.47749054673597696
0.36333333333333334
0.48095968877050627
0.36966666666666664
0.4827144313382626
0.374
0.4838636171484688
0.373
0.48360210917654195
0.3383333333333333
0.4731425671918443
0.36766666666666664
0.4821699792489044
0.3626666666666667
0.48076975316210935
0.358
0.47941214002150595
0.368
0.4822613399392491


In [36]:
# Estimate Transition Matrix
predict_noise3 = clf3.predict_proba(Xts)

#choose 3 representative rows/(3 max probabilty in each column)
print(np.argmax(predict_noise3[:,0]))    # 1st column max number index
print(np.argmax(predict_noise3[:,1]))    # 2ed column max number index
print(np.argmax(predict_noise3[:,2]))    # 3rd column max number index

1087
2660
1177


In [37]:
transition_matrix = np.array([predict_noise3[1087], predict_noise3[2660], predict_noise3[1177]])
transition_matrix

array([[0.62001857, 0.2012565 , 0.17872493],
       [0.21313697, 0.60168715, 0.18517588],
       [0.20955142, 0.25031104, 0.54013753]])

In [38]:
# RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=10,max_depth=7)

time = 10
for i in range(time):
    X_train, X_test, y_train, y_test = train_test_split(Xtr_val, Str_val,test_size=0.2)
    clf3.fit(X_train, y_train)
    
    matrix_inv = np.linalg.pinv(transition_matrix)

    predict_noise3 = clf3.predict_proba(X_test)
    predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

    predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
    predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

    print((predict_result_clean3 == y_test).mean()) #adjusted
    print((predict_result_clean3 == y_test).std()) #adjusted
    print((predict_result_noise3 == y_test).mean()) 
    print((predict_result_noise3 == y_test).std()) 

0.3576666666666667
0.47931328191718436
0.35833333333333334
0.4795107460271934
0.3463333333333333
0.47580096212130085
0.347
0.4760157560417512
0.3566666666666667
0.4790151934495977
0.357
0.47911480878803986
0.3516666666666667
0.47749054673597696
0.35133333333333333
0.4773868685062695
0.3393333333333333
0.4734830749057692
0.3373333333333333
0.4727996991914817
0.3556666666666667
0.478714830445944
0.35433333333333333
0.4783108008630186
0.346
0.4756931784249171
0.3443333333333333
0.47515038555060535
0.346
0.47569317842491715
0.345
0.4753682782853732
0.35133333333333333
0.47738686850626955
0.34933333333333333
0.4767594315328807
0.35633333333333334
0.4789153253852802
0.355
0.478513322698543


In [80]:
clf3.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(transition_matrix)

predict_noise3 = clf3.predict_proba(Xts)
predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

print((predict_result_clean3 == Yts).mean()) #adjusted
print((predict_result_clean3 == Yts).std())

print((predict_result_noise3 == Yts).mean()) 
print((predict_result_noise3 == Yts).std())

0.434
0.49562485813364937
0.49566666666666664
0.499981221869604


In [74]:
clf3.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(matrix1)

predict_noise3 = clf3.predict_proba(Xts)
predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

print((predict_result_clean3 == Yts).mean()) #adjusted
print((predict_result_clean3 == Yts).std())

print((predict_result_noise3 == Yts).mean()) 
print((predict_result_noise3 == Yts).std())

0.5346666666666666
0.49879677447054754
0.491
0.49991899343793694


In [75]:
clf3.fit(Xtr_val, Str_val)
matrix_inv = np.linalg.pinv(matrix2)

predict_noise3 = clf3.predict_proba(Xts)
predict_noise_adjusted3 = np.dot(matrix_inv, predict_noise3.T)

predict_result_clean3 = np.argmax(predict_noise_adjusted3, axis = 0)
predict_result_noise3 = np.argmax(predict_noise3, axis = 1)

print((predict_result_clean3 == Yts).mean()) #adjusted
print((predict_result_clean3 == Yts).std())

print((predict_result_noise3 == Yts).mean()) 
print((predict_result_noise3 == Yts).std())

0.5113333333333333
0.49987153905334075
0.5113333333333333
0.49987153905334075
